services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
  certbot:
    image: redxef/certbot-duckdns
    container_name: certbot
    restart: unless-stopped
    environment:
      DUCKDNS_DOMAIN: ${DUCKDNS_DOMAIN}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN}
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot

volumes:
  certbot_conf:
  certbot_www:
